title: ""
description: "Open-access fusion research platform"
baseurl: ""  # Vuoto per GitHub Pages su dominio user.github.io
url: "https://tokalab.github.io"

# Percorso locale al logo (deve esistere nella cartella /assets/images)
logo: /assets/images/logo.png

# Disabilita il tema remoto o installato via gem
theme: null

# Abilita plugin consentiti da GitHub Pages
plugins:
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-archives

# Skin (opzionale, cambia lo stile generale del sito)
minimal_mistakes_skin: "default"

# Navigation (se usi _data/navigation.yml)
navigation:
  enabled: true
  style: "overlay"
